# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e467a00b9e91ccd6a74a87f57a8603bd"
application_url = "https://thumb-instruments-gods-final.trycloudflare.com"
embedded = true
name = "Organifi"
handle = "organifi-3"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_discounts,write_discounts,write_products"

[auth]
redirect_urls = [
  "https://thumb-instruments-gods-final.trycloudflare.com/auth/callback",
  "https://thumb-instruments-gods-final.trycloudflare.com/auth/shopify/callback",
  "https://thumb-instruments-gods-final.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
include_config_on_deploy = true
dev_store_url = "organifi-tests.myshopify.com"
automatically_update_urls_on_dev = true
