api_version = "2024-07"

[[extensions]]
name = "t:name"
handle = "shipping-rate-bundle"
type = "function"

description = "t:description"

  [[extensions.targeting]]
  target = "purchase.shipping-discount.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
    create = "/app/shipping_rate_bundle/:functionId/new"
    details = "/app/shipping_rate_bundle/:functionId/:id"

[extensions.input.variables]
namespace = "$app:shipping-rate-bundle"
key = "selectedCollectionIds" 
