api_version = "2024-04"

[[extensions]]
name = "t:name"
handle = "shipping-rate"
type = "function"

description = "t:description"

  [[extensions.targeting]]
  target = "purchase.shipping-discount.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
    create = "/app/shipping_rate/:functionId/new"
  details = "/"
