name: Deploy app
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install npm dependencies
        run: npm install
      - name: Install Shopify CLI
        run: npm install -g @shopify/cli@latest
      - name: Deploy
        env:
          # Token from the Partner Dashboard
          SHOPIFY_CLI_PARTNERS_TOKEN: "atkn_fc2845e23c9cef78e402616e5fe8dc36e9e20567aadca02547ac5f3949e895d3"
          COMMIT_URL: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}
          # .env content after a deploy
          SHOPIFY_API_KEY: "e467a00b9e91ccd6a74a87f57a8603bd"
        run: shopify app deploy -f --source-control-url "$COMMIT_URL"